version: "3.9"
services:
  
  db:
    image: postgres
    container_name: db
    user: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  main:
    build: .
    container_name: main
    environment:
      - TZ=Europe/Bratislava
    depends_on:
      db:
        condition: service_healthy